---
title: "6: Lexis Expansion Cohort Studies"
subtitle: "R 4 ASME"
author: Lakmal
output: html_notebook
---

Load libraries

```{r}
library(epiDisplay)
library(magrittr)
library(forcats)
library(ggfortify)
library(expss)
library(epitools)
library(haven)
library(psych)
library(tidyverse)
library(Epi)
library(survival)
library(rockchalk)
```

Data wrangling

```{r}
whitehall <- read_dta(choose.files()) %>% mutate_if(is.labelled, as_factor)
View(whitehall)

# Create a variable that has the number of days betweens timein and timeout
whitehall$followup <- as.numeric(whitehall$timeout - whitehall$timein)
summary(whitehall$followup)

```

Use of Poisson regression to determine the rate of events 

```{r}

# Fitting a poisson model with the outcome of all with time variable which has to be offset log in poisson 
m1 <- whitehall %>% glm(all ~ offset(log(followup)), family = "poisson", data = .)
summary(m1)


# If we want to calculate rate ratios by job type
m2 <-
  whitehall %>% glm(chd ~ offset(log(followup)) + grade, family = "poisson", data = .)
summary(m2)
exp(m2$coefficients)

# Create a variable age at exit
whitehall$ageout <- whitehall$agein + (whitehall$followup / 365.25)
summary(whitehall$ageout)


```

Lexis Expansion 

```{r}
# First ensure that the dates are the correct calendar format - this is the decimal age 
whitehall$timein <- cal.yr(whitehall$timein, format="%d/%m/%Y")
whitehall$timeout <- cal.yr(whitehall$timeout, format="%d/%m/%Y")
whitehall$timebth <- cal.yr(whitehall$timebth, format="%d/%m/%Y")

# Create the lexis object, this enables multiple timescales to be determined - in this I have created 3 labelled per(year), age (current age), fut (time since entry/follow up)
Lexis.whitehall.chd <- whitehall %>% Lexis(entry = list(per=timein), exit = list( per=timeout, age = timeout - timebth, fup = timeout - timein), exit.status = chd, data = . )
View(Lexis.whitehall.chd)

# Plot the lexis object - THIS IS OPTIONAL 
plot(Lexis.whitehall.chd, grid=0:20*5, col="black", xaxs="i", yaxs="i", xlim=c(1960,1978), ylim=c(35,80), lwd=3, las=1 )

```

Classical Analysis

```{r}

# Split the lexis object by age - this is equivelent to the stplit command - chose when the breaks are 
Lexis.WC.age.split <- splitLexis(Lexis.whitehall.chd, breaks = c(40, seq(50, 80, 5)), time.scale="age" )
# Add a variable to the lexis object with the age category
Lexis.WC.age.split$age.cat <- timeBand(Lexis.WC.age.split, "age", type = "factor")

# Create a seperate lexis object split by period
Lexis.WC.period.split <- splitLexis(Lexis.whitehall.chd, breaks = seq(1965,1990,5), time.scale="per")
Lexis.WC.period.split$per.cat <- timeBand(Lexis.WC.period.split, "per", type = "factor")


# NB we can split a lexis object by both period and age and fup if we want to - just run the split command in sequence to create a final Lexis object with all the splits

# Rate in each lexis age period
Lexis.WC.age.split %>% group_by(age.cat, grade) %>% summarise(no = sum(lex.Xst), 
                                                       follow.up = sum(lex.dur), 
                                                       rate = no/follow.up*1000, 
                                                       lower.CI = rate/(exp(1.96*sqrt(1/no))),
                                                       upper.CI = rate*(exp(1.96*sqrt(1/no))))

# Rate in each lexis period - same code as above - just pipe the lexis object split by period
Lexis.WC.period.split %>% group_by(per.cat) %>% summarise(no = sum(lex.Xst), 
                                                       follow.up = sum(lex.dur), 
                                                       rate = no/follow.up*1000, 
                                                       lower.CI = rate/(exp(1.96*sqrt(1/no))),
                                                       upper.CI = rate*(exp(1.96*sqrt(1/no))))

# Is there a similar command to mhor to perform stratified rate ratio?

```


Performing regression on the lexis object 

```{r}


# Crain Higgins decided to collapse factors 
Lexis.WC.age.split$age.cat <- fct_collapse(Lexis.WC.age.split$age.cat, "(50,55]" = c("(-Inf,40]","(40,50]", "(50,55]"), " (70,75]" = c(" (70,75]","(75,80]", "(80,Inf]"))

# Create a variable in the lexis object with the age/period category can chose interger if we want log linear (continous) or factor if we want to fit mutliple paramters
Lexis.WC.age.split$age.cat <- timeBand(Lexis.WC.age.split, "age", type = "factor")

# The create the model with glm possion - NB INTERACTIONS MUST BE FITTED using the colon 
# The outcome is lex.Xst (whether in this case chd - as when creating the lexis object exit.status = chd), time is always offset log, then add covariates 
m2a <- (glm(lex.Xst ~ offset(log(lex.dur)) + as.factor(grade) +  age.cat + age.cat:as.factor(grade), family = poisson(), data = Lexis.WC.age.split))
exp(m2a$coefficients)

# Fit the same model without interactions
m2b <- (glm(lex.Xst ~ offset(log(lex.dur)) + as.factor(grade) +  age.cat, family = poisson(), data = Lexis.WC.age.split))
exp(m2a$coefficients)

# LRTest to test the evidence for interaction 
lrtest(m2a, m2b)


```

